### ISSUE TITLE
شماره سفارت خانه ها

### ISSUE THREAD

**Issue by jadijadi** [jadijadi/pishshomare#35]
اطلاعات اضافه شده و کدها هم. ولی ظاهرا کار نمی کنه. چرا؟

**Comment by a-goodarzi** [comment]
سلام. من روی فایرفاکس ۵۴ هستم و برای من اوکی هست. هم دیتا رو میاره و هم وقتی اسم یه سفارت خونه رو سرچ می‌کنم فیلترش درست عمل می‌کنه.

**Comment by jadijadi** [comment]
مرسی که تست کردی. مشکلش توی کد بود. دو سه تا کامیت کردم و درست نشد و بالاخره مجبور شدم روی کامپیوتر خودم هم تست کنم و درست کردمش (:
